server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  application:
    name: CloudMessagingServer
  jackson:
    serialization:
      indent_output: true
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    data-username: sa
    data-password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  scheduler:
    cron-regex: '0 * * * * *'
    message:
      title: 'Time to drink water'
      body: "Time to drink water, it's needed for you. Stop your work and drink water"
